version: '3'

services:

  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    command: >
      bash -c "npm run typeorm:run-migrations && npm run test:all && npm run start:dev"

  db:
    container_name: db
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}